# Step 1: Build the React app
FROM node:18 AS build

# Set the working directory
WORKDIR /app

# Set environment variable to use OpenSSL legacy provider
ENV NODE_OPTIONS=--openssl-legacy-provider

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# Step 2: Serve the React app using a web server
FROM nginx:alpine

# Copy the build folder from the previous stage to NGINX's html folder
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Command to run NGINX
CMD ["nginx", "-g", "daemon off;"]