#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  datafiles:

services:
  #DataBase Service
  database:
    #Pull the latest mysql image
    image: mysql:latest
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "3306:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - datafiles:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: Tinkerbell4
      MYSQL_USER: root
      MYSQL_PASSWORD: Tinkerbell4
      MYSQL_DATABASE: Civitas
  #Api  Service
  api:
    build: ./backend
    depends_on: 
      - database
    ports:
      - "5250:80"
    restart: always
    #Specify Environment Variables for the Api Service
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
