# Use the official .NET 8.0 SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy and restore the specific project file
COPY ["api/api.csproj", "api/"]
RUN dotnet restore "api/api.csproj"

# Copy the rest of the files and build the project
COPY . ./
RUN dotnet publish "api/api.csproj" -c Release -o out

# Build a runtime image using the ASP.NET runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copy the published output from the build image
COPY --from=build-env /app/out .

# Expose port 80
EXPOSE 80

# Run the application
ENTRYPOINT ["dotnet", "api.dll"]